Vulcanize Foundation release bits for API Scan tool
microsoft/WindowsAppSDK pull request #553
Opened 2021-03-11 00:24 UTC by kythant

Vulcanize Foundation release bits for API Scan tool

2021-03-12 08:19 UTC, BenJKuhn approved these changes

2021-03-13 05:51 UTC, jonwis requested changes

2021-03-13 05:51 UTC, jonwis commented on dev/ProjectReunion_DLL/ProjectReunion_DLL.vcxproj
> +      <AdditionalOptions>/debug /debugtype:cv,fixup /opt:ref /opt:icf /incremental:no %(AdditionalOptions)</AdditionalOptions>
Please change this to use a model like:

```xml
<AdditionalOptions>$(AdditionalPipelineLinkerOptions) %(AdditionalOptions)</AdditionalOptions>
```

Where that "additional pipeline" value is set by the ADO build pipeline as necessary. This lets us configure the linker commands during official build runs but not impact the individual developer's output.

2021-06-30 05:32 UTC, BenJKuhn commented
@kythant, I'm closing old or abandoned pull requests. If you'd like to revisit this and pick it up again, feel free to reopen when you're ready to work on it. @alexlamtest can you confirm that this change is no longer necessary?

2021-06-30 05:32 UTC, closed without merging